### ISSUE TITLE
327.7

### ISSUE THREAD

**Issue by jpduyx** [royduin/home-assistant-incomfort#1]
Hi Roy,

I'm new to HomeAssistant and installed it to use your module to controll my Intergas Boiler 

Used the docker installation and put the InComfort.py in the subfolder of the docker path, eg:

> mypath/custom_components/climate/InComfort.py

and added the example config to configuration.yaml

So far so good. 

But I'm wondering why Home Assistant thinks its a good idea to try to heat my house to 327.7 °C?

Trying to adjust the to what i want takes probably longer (0.5 degrees per click in the Gui) than asking here how I can configure a more useful number as default target temperature.  (I haven't set up any automation in Hass yet because Im  playing with the possibilities in a docker container in my laptop ...

**Comment by royduin** [comment]
What are the temperatures in the Incomfort web interface? Just visit the IP address in the browser. Can you send me the source code of the page where the temperatures are displayed? Right click on the page there is an option to view the source.

**Comment by jpduyx** [comment]
Nowhere in the rf2lan interface i see this 327.7. 

I'll think I first have to understand HomeAssistant before trying to understand this module ... 


- ubuntu linux laptop with docker based home-assistance
- rf2lan connected to router and configured working with phone app and boiler 
- Wired Chronotherm is Off / freezing protection mode
- WIreless CMS927 set to 17.5. 
- HomeAssistant set to 18.5 manually

The temperature of 327.7 in Home-Assistant is just displayed on the "Overview" under the welcome message, seems to be a 'javascript voodo' thing that displays that message there. 

When i Customize "my_temperature" through  http://localhost:8123/config/customize
I get a new file customize.yaml wich then holds a more decent default like 19 degrees also after restart of HA. 

> cat customize.yaml
> climate.my_temperature
>   temperature: 19

OH i found also something in the thread about the feature request that comes very close to the strange default of 327.7 
>    if (room_set2 != 327.67){
>	document.getElementById('room_set2').innerHTML = room_set2;

Maybe it is some default number that comes from somewhere in the rf2lan that is being rounded somewhere to 327.7 in HA?

Readings from the rf2lan: 

```
Room temperature 1: 17.68
Room setpoint 1: ...
Room setpoint override 1: 18.5
Room temperature2: ...
Room setpoint 2: 17.5
Room setpoint override 2: 0
```

**Comment by jpduyx** [comment]
when I switch the CMS927 to OFF ("vorst"), I get:

> Room setpoint 2: 325.11

That made me wondering if the 327.7 perhaps came from the wired thermostat that has been configured to to OFF ("vorst") or some other predefined "Off" state of Opentherm?

**Comment by royduin** [comment]
I think 327.67 is the "off" state, I've just added support for that. 327.67 should be 0 now. Let me know if it's working.

**Comment by royduin** [comment]
@jpduyx, is it working now?

**Comment by jpduyx** [comment]
looks a bit better, although i would prefer if it would state 5 degrees, the minimal value on "Vorst" / Feezing Protection mode on my Room Thermostat  ... or 6 degrees, as the minimal number in the InComort App?

**Comment by jpduyx** [comment]
Or should it show active "Manual Override" that we set manually with InComfort / HomeAssistant, whatever is controlling the Heater at the moment? 

Its still confusing what the numbers mean in the InComfort thingy ... and I haven't been able to find a technical reference yet from Intergas which explains the use of the numbers a bit more ...

**Comment by royduin** [comment]
Changed it to 5 instead of 0, see: https://github.com/royduin/home-assistant-incomfort/commit/210e0b63e201d58d184e6b8e32b2b0e631373407, when visiting the Incomfort web app the minimum value is also 5 degrees.

From the Incomfort web app (just visit the IP address of the gateway in the browser) there is only 1 option to change; the temperature (5 to 30 range). Do you have more options? Or do you mean the 327.67, that's the only "non real" temperature. Don't see what's confusing anymore?

**Comment by jpduyx** [comment]
THere are different minimal values from the user perspective: 

rf2lan module /  WebAp: 5Android App: 6Wired Wall thermostat: 5 
Wireless Wall thermostat: : ? 

And i think I do have a wired / or wireless Wall thermostat where i can manually set the  'VORST' / 'OFF' / 'Freezing Protection' Temperature between 5 and 10 degrees Celsius on the wall module. So 5 isn't a clear fixed value for 'off' state it seems. 


Did you find clear documentation from Intergas with examples how to read / control the InComfort rf2lan module through its API in different scenario's (for example with a wired OpenTherm thermostat, a Wireless RF Thermostat + rf2lan module +   webapp + Android app + HomeAutomation what happens / is supposed to happen in what combination of settings in different possible scenario's?
As far as i can see there are 2 values in the rf2lan module for 2 thermostats. So in total 4 values. 
And I'm not sure if that includes the values of the extra WIRELESS thermostat that I also have connected to my Intergas Heater. Or that it is only shows the values of the Wired wall thermostat plus the values in the InComfort App / rf2lan module? 

I would expect the InComfort in HomeAutomation Overview page, give a transparent overview of all  the (4?) possible values (overrides, and default value of thermostat 1 and thermostat 2) ... OR the "DOMINANT" value according to the rules that OpenTherm protocol and the Boiler itself is now acting on. 

But to understand what would happen in what scenario, some more technical documentation from Intergas would be appreciated IMHO. 



Met vriendelijke groet, 

Jean-Paul 

    Op zaterdag 29 december 2018 20:07:27 CET schreef Roy Duineveld <notifications@github.com>:  
 
 
Changed it to 5 instead of 0, see: 210e0b6, when visiting the Incomfort web app the minimum value is also 5 degrees.

From the Incomfort web app (just visit the IP address of the gateway in the browser) there is only 1 option to change; the temperature (5 to 30 range). Do you have more options? Or do you mean the 327.67, that's the only "non real" temperature. Don't see what's confusing anymore?

**Comment by royduin** [comment]
The documentation can be found here: https://community.home-assistant.io/t/intergas-incomfort-lan2rf-gateway/23967/4, currently my implementation has the first heater / thermostat hardcoded see; https://github.com/royduin/home-assistant-incomfort/blob/210e0b63e201d58d184e6b8e32b2b0e631373407/InComfort.py#L105

As I don't have more heaters or thermostats I can't help you with that but you can experiment with those values. Maybe duplicate the code and have different heater / thermostat id's. Any improvements are welcome through a PR.

**Comment by jpduyx** [comment]
Thanks, I tried the new version... Still see something strange happening. 

Maybe Due to my setup with multiple thermostats, but the Target Temperature changes in the HA "PopUP" when i click on the temperature area in the Climate section on the HA main screen. 

I can set a new target temperature to eg 7. Then I see a message that new target is being set. 

![incomfort_target_tem_not_shown_on_main_dashboard_only_pop-up_home assistant](https://user-images.githubusercontent.com/25197089/50551325-138e8d00-0c7f-11e9-8436-10a18d642f98.png)

But some minutes later the target temperature is still the same (5 degrees).
Only the popup shows the  7 degrees.

**Comment by royduin** [comment]
That's normal. Wait a few minutes more, I've changed it here: https://github.com/royduin/home-assistant-incomfort/commit/78aab738df0acaf1e8b8cc2476e0270846ad32b6. Previously the temperature was reflected directly when changed in Home Assistant because it used the override temperature. But when you change the temperature from the thermostat it wasn't visible in Home Assistant. Now I'm using the thermostat temperature, but that one isn't updated directly.

**Comment by jpduyx** [comment]
Thnx for the reply.

Maybe that doesn't work the same in my case, NOT using a Honeywell round modulation, but an older wired opentherm that already marked its spot on my wall from hanging there many years, plus the wireless in another room, plus the rf2lan that also is trying to set temperatures. Different setup might have different unexpected results. Maybe my old thermostat will never reflect the temperature set by home-assistant so the code won't be able to read it from the thermostat?

OpenTherm seems to be a closed source protocol and maybe my old thermostat isn't same opentherm as the round modulation that Intergas advises to use with the rf2lan? And that combined with the RF thermostat that also talks with the heater ... 


I asked Intergas for more documentation about rf2lan with more examples for different scenario's, like mine with a wired and a RF thermostat and the rf2lan that I was t to integrate with home automation software.

Their answer was that they used to have documentation for clients, but now don't have it or don't supply it ... 
I found it a strange answer. So 
I asked to put my question higher in the organisation or connect me or you with their software developer to get more information or to put example code here on GitHub to help their customers integrate their product in home automation systems. 


I keep trying and will keep you updated.


Kind regards happy new year !

Jean-Paul



--

**Comment by royduin** [comment]
Looking forward to the updates, happy new year!

**Comment by royduin** [comment]
Closing this due inactivity and the original issue is resolved.
