### ISSUE TITLE
request to match HA climate new thermostat modes (eg is heating state and inactive state)

### ISSUE THREAD

**Issue by KeningGruttePier** [royduin/home-assistant-incomfort#10]
this integration adds the incomfort thermostat to home assistant. 

nowadays the thermostat entity class in HA supports more functionalities. can this incomfort integration be update d to eg also reflect state of heating active and inactive state for the thermosstat?

**Comment by royduin** [comment]
This is an old custom integration; HA currently has built in support voor Incomfort. You should use that.
