### ISSUE TITLE
Display Heater status

### ISSUE THREAD

**Issue by sirfooey** [royduin/home-assistant-incomfort#2]
Hello, 

Great work - my setup is a bit different as I use EvoHome to control the boiler, however, the RF Gateway does have some stats that I would like displayed in Home Assistant - namely, heater (CH) temp, tap (DHW) temp, pressure, display code

http://<intouchgatewayIP>/status.htm?heater=0

Any chance your next version could accommodate this?

Thanks

**Comment by sirfooey** [comment]
Cancel that - worked out that you can view the JSON

/data.json?heater=0

And then simply use the restful sensor to display

**Comment by royduin** [comment]
For people coming by; I've added some information to the readme how this can be achieved: https://github.com/royduin/home-assistant-incomfort#show-more-information
