### ISSUE TITLE
Component is broken with Home Assistant 0.89

### ISSUE THREAD

**Issue by JayOne73** [royduin/home-assistant-incomfort#3]
With the change in the custom components in Home Assistant, this component does not load anymore from release 0.89 (don't know sure about 0.88, because 0.87 was my latest version).

According to this [forumpost](https://gathering.tweakers.net/forum/view_message/58262334), the climate-components needs some rewrite and new folder-structure.

**Comment by royduin** [comment]
Thanks for reporting! I'm looking into this within 2 weeks.

**Comment by anlupat** [comment]
only change needed:

Line 8 & 9

from homeassistant.components.climate import (ClimateDevice, PLATFORM_SCHEMA)
from homeassistant.components.climate.const import (
    STATE_HEAT, SUPPORT_TARGET_TEMPERATURE)

**Comment by JayOne73** [comment]
I can confirm that with the above changes the component seems to work again.  

This was the code I used:

`from homeassistant.components.climate import ClimateDevice, PLATFORM_SCHEMA`
`from homeassistant.components.climate.const import (`
`    STATE_HEAT, SUPPORT_TARGET_TEMPERATURE)`
`from homeassistant.const import (`
`    TEMP_CELSIUS, ATTR_TEMPERATURE)`

with using the following folderstructure: custom_components/InComfort/climate.py

**Comment by royduin** [comment]
For reference: https://github.com/royduin/home-assistant-incomfort/pull/4

**Comment by royduin** [comment]
Fixed by #4 and created a new release.
