### ISSUE TITLE
Hassio config check: platform.incomfort not found

### ISSUE THREAD

**Issue by Ruudtb205** [royduin/home-assistant-incomfort#5]
Hello,
I’m not sure if I’m in the right section, but I couldn’t decide where to go, so here it is…
I upgraded Hasio from 0.88.1 to 0.90.1. Everything works, but for my climate config.
I use this repository from github: https://github.com/royduin/home-assistant-incomfort
In 0.88.1 it worked like a breeze, but since the update it is broken. This is how I set it up:
I created a folder in `config/custom_components`: `incomfort`. In that folder I copied `climate.py`. In `configuration.yaml` I added:

```
# Klimaat controle
climate:
  - platform: incomfort
    name: Woonkamer
    host: 192.168.0.3
```

But when I check my configuration I get the error: `Platform not found: climate.incomfort`. In the loggin I first see that same error, and later on it says:
```
Mon Mar 25 2019 21:07:59 GMT+0100 (West-Europa (standaardtijd))

Error loading custom_components.incomfort.climate. Make sure all dependencies are installed

`Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file module = importlib.import_module(path) File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "&lt;frozen importlib._bootstrap&gt;", line 1006, in _gcd_import File "&lt;frozen importlib._bootstrap&gt;", line 983, in _find_and_load File "&lt;frozen importlib._bootstrap&gt;", line 967, in _find_and_load_unlocked File "&lt;frozen importlib._bootstrap&gt;", line 677, in _load_unlocked File "&lt;frozen importlib._bootstrap_external&gt;", line 728, in exec_module File "&lt;frozen importlib._bootstrap&gt;", line 219, in _call_with_frames_removed File "/config/custom_components/incomfort/climate.py", line 6, in &lt;module&gt; from homeassistant.components.climate import ( ImportError: cannot import name 'STATE_HEAT' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py)`
```
I searched Github and the Forum, but no luck…
Can anybody point me in the right direction? Help is much appreciated!

**Comment by royduin** [comment]
Hi @Ruudtb205, what you're doing should work. Please double check and make sure you've got the latest version of the `climate.py` file.

**Comment by Ruudtb205** [comment]
That dit the trick: my climate.py was outdated. Copied the latest version and it works perfectr, like before. Thanks a lot for helping me out, really like your tool!
