### ISSUE TITLE
Integration InComfort not found when trying to verify its climate platform.

### ISSUE THREAD

**Issue by amargedon** [royduin/home-assistant-incomfort#8]
Upgraded yesterday my Home Assistant from (I think) 0.87 to the latest version. This control was working fine (thanks for the work, by the way!), however after the upgrade I'm missing the control from the main overview. Also the state sensors which I had do not get any data anymore.

I checked the connection to the gateway, which is working fine (I do see the json output using the URL from the source code). 

Removed the folder/file from the custom components, removed the part in the configuration. Re-added everything and still nothing. Validation of the configuration produces something which I don't understand: _Integration InComfort not found when trying to verify its climate platform_.

When I remove the climate: part (as mentioned in the Readme) this message is gone, logically (but to rule out other problems). No errors in the logfile.

Any ideas what to try further?

Home Assistant 0.92.0
Latest climate.py

**Comment by royduin** [comment]
The custom component directory structure changed in 0.89, see: 
- https://www.home-assistant.io/blog/2019/03/06/release-89/#noteworthy-breaking-changes
- https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html

Change your structure and naming to: `custom_components/InComfort/climate.py`

**Comment by amargedon** [comment]
Thanks for the quick reply!

The folder structure is already as you mentioned; I followed this morning the Readme (again) and recreated the structure (and configuration) as described.

**Comment by royduin** [comment]
Sorry, there where also some changes in 0.92: 
- https://developers.home-assistant.io/blog/2019/04/12/new-integration-structure.html

I'm still on 0.91.4 so I didn't see it.

Could you try creating a empty `__init__.py` and a `manifest.json` with:
```
{
  "domain": "InComfort",
  "name": "InComfort",
  "documentation": "https://github.com/royduin/home-assistant-incomfort",
  "dependencies": [],
  "codeowners": ["@royduin"],
  "requirements": []
}
```
In the InComfort directory? If that's working I'll add it to the repo and modify the readme.

**Comment by amargedon** [comment]
Yes; found it and so did you! After reading the pages you mentioned I ended up at the same new-integration-structure page. I did create an empty `__init__.py` and that solved it; now it's working and I can see the element on the overview page.

Did try to create only the `manifest.json` file with the mentioned content; no luck. So this file seems optional.

**Comment by royduin** [comment]
Thanks for testing and good to hear it's working! I've updated everything and tagged a new release.

**Comment by furian88** [comment]
Hi Roy,

i dont know why it doesn't work at my setup. i've replaced all the files you mentioned and eventually found this page.
So i made an empty init file and added the code to manifest.json.. this finally made my config lose the text saying it can't find the InComfort integration.

however this made my config make a loop and i get nothing more then a spinning circle..
any idea?

edit:even worse, after a reboot the entire hassio page wont load anymore till i remove the files..

**Comment by royduin** [comment]
Have you exactly followed these steps? https://github.com/royduin/home-assistant-incomfort#installation any errors in the logs?

**Comment by furian88** [comment]
ah allready found out what the problem was.. made a config error.
so nvm me :)
