### ISSUE TITLE
HA 0.93: Add Intergas InComfort Lan2RF gateway

### ISSUE THREAD

**Issue by JayOne73** [royduin/home-assistant-incomfort#9]
In HA 0.93 the Intergas InComfort gateway will be added as [new platform](https://rc.home-assistant.io/blog/2019/05/08/release-93/)

**Comment by royduin** [comment]
Yeah, I was following this one: https://github.com/home-assistant/home-assistant/pull/23591 but apparently he created another PR: https://github.com/home-assistant/home-assistant/pull/23736. Didn't know that. No idea what the difference is between them but let's try it when it's released and see if it can replace this custom component.

**Edit:** In 0.93 is just some water heater information, not the central heating system. That's the other PR.

**Comment by bvduijv** [comment]
According to documentation it is limited to temperature and state. No control (yet)

See https://rc.home-assistant.io/components/incomfort/

**Comment by JayOne73** [comment]
In HA 0.94 the climate component will also be added.

https://github.com/home-assistant/home-assistant/pull/23830
https://rc.home-assistant.io/blog/2019/05/29/release-94/#new-platforms

**Comment by royduin** [comment]
When it's released and I've updated my installation I'll try it and see if it works as this module does.

**Comment by Palerm0** [comment]
Hi,
I m new to HA, and I`m trying to get my intergas Lan2RF into home assistance. 
I followed lots of manuals and tips.  
I have version 0.100.3 of home assistant installed. 

In the Yaml Configuration I have the following:
incomfort:
  host: 192.168.xxx.xxx
  username: admin
  password: intergas

The verification according HA says  Configuration valid!
But Notifications shows me an mark 
Invalid config
The following components and platforms could not be set up:
incomfort
Please check your config.

Am i missing something?

Greetings
Palermo

**Comment by royduin** [comment]
Sorry can't help you with that, try the support forums of Home Assistant. This is an old custom integration before Incomfort support was added to Home Asssistant.

And to come back on the subject of this issue; I'm still running 0.91.4 so I did not try the new integrations yet. I hope to upgrade before the end of the year.

**Comment by Palerm0** [comment]
Hoi Roy,
Ok I`l Look for the support forums.

Thanks for pointing me in the right direction
Gr Palermo

**Comment by Michelli** [comment]
Try removing the username and password.

**Comment by Palerm0** [comment]
Hi,
Thanks for helping.
I removed the U and P. It still shows me the invalid configuration. May be the new version broke something. 

I also open a question in the [HA support forum](https://community.home-assistant.io/t/add-intergas-incomfort-lan2rf-gateway-version2/144491)

Again Thanks
